(**
---
title: Signatures
description: Describes the public elements in an F# program. Generated by the compiler. Can be edited to remove elements to make them private.
keywords: header private compiler public
---

*)
