title: "games-matter.com"
description:
  A blog about the progress of Matter, a new game I'm working on. Topics such as
  JavaScript, 3D, physics, Real-time strategy (RTS) will be discussed as well
  as the games industry in general and how I hope to make it a better place.

links: # see http://fontawesome.io/icons/#brand for all possible icons
  - linkedin: "https://www.linkedin.com/in/phil-a-thompson-83b64a2/"
  - twitter: "https://twitter.com/PhilAThompson/"
  - github: "https://github.com/PhilT"
  - envelope: "mailto:phil@games-matter.com"

