title: electricvisions.com
description: This is the website of Electric Visions Ltd. A software consultancy turned games company. Here you'll find articles on developing on Windows, Linux, Ruby, .NET Core, F#, AWS, (Neo)Vim and game design/development.
linkedin: https://www.linkedin.com/in/phil-a-thompson-83b64a2/
twitter: https://twitter.com/PhilAThompson/
github: https://github.com/PhilT
envelope: mailto:phil@electricvisions.com
css: colours.css imports.css
