title: (none)
description: (none)

links: # see http://fontawesome.io/icons/#brand for all possible icons
  - linkedin: "https://www.linkedin.com/in/phil-a-thompson-83b64a2/"
  - twitter: "https://twitter.com/PhilAThompson/"
  - github: "https://github.com/PhilT"
  - envelope: "mailto:phil@games-matter.com"
